import type { ApplicationType, JobType } from './types';

export const initialJobs: JobType[] = [
  {
    id: 1,
    company: '카카오',
    description: '더 나은 세상을 만드는 기술과 사람을 연결합니다.',
    positions: ['프론트엔드', '백엔드'],
    employment: '정규직',
    deadline: '2026.07.28',
    dday: 8,
    featured: true,
    applicants: 12,
    status: '모집중',
  },
  {
    id: 2,
    company: '토스',
    description: '금융의 모든 순간을 쉽고 간편하게 바꿉니다.',
    positions: ['백엔드', 'DevOps'],
    employment: '산업기능요원',
    deadline: '2026.07.24',
    dday: 4,
    featured: true,
    applicants: 8,
    status: '모집중',
  },
  {
    id: 3,
    company: '당근',
    description: '동네의 새로운 연결을 만드는 로컬 커뮤니티입니다.',
    positions: ['프론트엔드'],
    employment: '인턴',
    deadline: '2026.08.02',
    dday: 13,
    applicants: 6,
    status: '모집중',
  },
  {
    id: 4,
    company: '네이버클라우드',
    description: '클라우드 기술로 산업의 디지털 전환을 돕습니다.',
    positions: ['AI', '클라우드'],
    employment: '계약직',
    deadline: '2026.07.18',
    dday: -2,
    applicants: 15,
    status: '마감',
  },
];

export const initialApplications: ApplicationType[] = [
  {
    id: 1,
    name: '김도윤',
    studentId: '2314',
    company: '카카오',
    position: '프론트엔드',
    date: '2026.07.18 14:32',
    email: 'doyun@gsm.hs.kr',
    phone: '010-2381-7721',
    status: '지원 완료',
  },
  {
    id: 2,
    name: '김도윤',
    studentId: '2314',
    company: '네이버클라우드',
    position: 'AI',
    date: '2026.07.12 09:10',
    email: 'doyun@gsm.hs.kr',
    phone: '010-2381-7721',
    status: '서류 합격',
  },
  {
    id: 3,
    name: '이서연',
    studentId: '2412',
    company: '카카오',
    position: '백엔드',
    date: '2026.07.17 16:45',
    email: 'seoyeon@gsm.hs.kr',
    phone: '010-5187-3412',
    status: '지원 완료',
  },
  {
    id: 4,
    name: '박준호',
    studentId: '2501',
    company: '토스',
    position: 'DevOps',
    date: '2026.07.16 11:24',
    email: 'junho@gsm.hs.kr',
    phone: '010-6731-2140',
    status: '서류 불합격',
  },
];
